# Generated by Django 2.2.6 on 2019-10-25 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0002_facebookpost_parent_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebookgroup',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
