# Generated by Django 2.2.6 on 2020-01-28 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0003_facebookgroup_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacebookUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook_login', models.CharField(max_length=50)),
                ('facebook_password', models.CharField(max_length=100)),
            ],
        ),
    ]
