# Generated by Django 2.2.6 on 2020-01-28 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0004_facebookuser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facebookgroup',
            options={'verbose_name': 'Grupa', 'verbose_name_plural': 'Grupy'},
        ),
        migrations.AlterModelOptions(
            name='facebookpost',
            options={'verbose_name': 'Post', 'verbose_name_plural': 'Posty'},
        ),
        migrations.AlterModelOptions(
            name='facebookpostcommentlvl0',
            options={'verbose_name': 'Komentarz', 'verbose_name_plural': 'Komentarze'},
        ),
        migrations.AlterModelOptions(
            name='facebookpostcommentlvl1',
            options={'verbose_name': 'Odpowiedź do komentarza', 'verbose_name_plural': 'Odpowiedzi do komentarzy'},
        ),
        migrations.AlterModelOptions(
            name='facebookuser',
            options={'verbose_name': 'Konto facebook', 'verbose_name_plural': 'Konta facebook'},
        ),
        migrations.AddField(
            model_name='facebookgroup',
            name='facebook_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='facebook.FacebookUser'),
            preserve_default=False,
        ),
    ]
