# Generated by Django 2.2.6 on 2020-01-28 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0005_auto_20200128_1015'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facebookuser',
            options={'verbose_name': 'Konto Facebook', 'verbose_name_plural': 'Konta Facebook'},
        ),
    ]
