# Generated by Django 2.2.6 on 2020-09-24 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0008_auto_20200924_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facebookpost',
            name='permalink',
            field=models.TextField(blank=True, null=True),
        ),
    ]
