# Generated by Django 2.2.6 on 2020-01-28 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='name',
            field=models.CharField(default='Domyślna konfiguracja', max_length=100, verbose_name='Nazwa'),
        ),
    ]
