# Generated by Django 2.2.6 on 2020-01-30 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0003_create_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='max_entry',
            field=models.IntegerField(default=10, help_text='Maksymalna liczba przeglądanych postów z wall-a konkretnej grupy', verbose_name='Max wpisów'),
        ),
    ]
