# Generated by Django 2.2.6 on 2020-01-30 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0005_create_cron_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='email_from',
            field=models.CharField(default='no-reply@kmagdziarz.pl', help_text='Adres e-mail nadawcy raportu', max_length=100, verbose_name='E-mail nadawcy'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='email_to',
            field=models.CharField(default='raport@kmagdziarz.pl', help_text='Adres e-mail odbiorcy raportu', max_length=100, verbose_name='E-mail odbiorcy'),
        ),
    ]
