# Generated by Django 2.2.6 on 2020-02-09 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0006_auto_20200130_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='capture_event',
            field=models.BooleanField(default=False, help_text='Zbieraj także powiadomienia o wszystkich event logach', verbose_name='Sentry capture event'),
        ),
    ]
