# Generated by Django 2.2.6 on 2020-02-09 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0007_configuration_capture_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='email_to',
            field=models.CharField(default='raport@kmagdziarz.pl', help_text='Adres e-mail odbiorcy raportu. Jeżeli chcesz dodać wielu odbiorców dodaj ich po przecinku: user1@poczta.com,user2@poczta.com', max_length=100, verbose_name='E-mail odbiorcy'),
        ),
    ]
